apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tan-dara5304-dara-gitlab-certificate
  namespace: tan-dara5304-dara-gitlab
spec:
  secretName: tan-dara5304-dara-gitlab-secret-tls
  commonName: tan-dara5304-dara-gitlab.assessify.org
  dnsNames:
  - tan-dara5304-dara-gitlab.assessify.org
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
